/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal_rodolfotorrescaballero_yonyhoyosmeza;


import java.util.Random;


import javax.swing.table.DefaultTableModel;
import static proyectofinal_rodolfotorrescaballero_yonyhoyosmeza.ProyectoFinal_RodolfoTorresCaballero_YonyHoyosMeza.bur;
import static proyectofinal_rodolfotorrescaballero_yonyhoyosmeza.ProyectoFinal_RodolfoTorresCaballero_YonyHoyosMeza.ini;

/**
 *
 * @author etorresr
 */
public class Burbujas extends javax.swing.JFrame {

    int n, m, x, y;
    Random r = new Random();
    boolean bandera = true, bandera2 = true;

    /**
     * Creates new form Burbujas
     */
    public Burbujas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        inicio = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tabla.setName(""); // NOI18N
        tabla.getTableHeader().setResizingAllowed(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        inicio.setText("Iniciar");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(inicio)
                .addGap(97, 97, 97)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicio)
                    .addComponent(salir)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        inicio.setText("Reinicio");
        n = r.nextInt(100) + 25;
        m = r.nextInt(70) + 25;
        DefaultTableModel tb = (DefaultTableModel) tabla.getModel();
        tb.setColumnCount(m);
        tb.setRowCount(n);
        tabla.getTableHeader().setUI(null);
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {
                tabla.setValueAt("◙", i, j);
                
            }
        }
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {

                tabla.setValueAt("•", r.nextInt(n), r.nextInt(m));
            }
        }
    }//GEN-LAST:event_inicioActionPerformed

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        y = tabla.getSelectedColumn();
        x = tabla.getSelectedRow();
        if ((tabla.getValueAt(x, y)).equals("◙")) {
            tabla.setValueAt("•", x, y);
            
            for (int i = 0; i < n; i++) {
                for (int j = 0; j < m; j++) {
                    if (i == x && j == y) {
                        if (x > 0 && x < n - 1) {
                            for (int k = 0; k < n; k++) {
                                if (k >= x - 1 && k <= x + 1) {
                                    if ((tabla.getValueAt(k, y)).equals("◙")) {
                                        tabla.setValueAt("•", k, y);
                                    }
                                }
                            }
                        }
                        if (y > 0 && y < m - 1) {
                            for (int k = 0; k < m; k++) {
                                if (k >= y - 1 && k <= y + 1) {
                                    if ((tabla.getValueAt(x, k)).equals("◙")) {
                                        tabla.setValueAt("•", x, k);
                                    }
                                }
                            }
                        }
                        if (x == 0) {
                            if (y == 0) {
                                if ((tabla.getValueAt(x + 1, y)).equals("◙")) {
                                    tabla.setValueAt("•", x + 1, y);
                                }
                                if ((tabla.getValueAt(x, y + 1)).equals("◙")) {
                                    tabla.setValueAt("•", x, y + 1);
                                }
                            } else if (y == m - 1) {
                                if ((tabla.getValueAt(x + 1, y)).equals("◙")) {
                                    tabla.setValueAt("•", x + 1, y);
                                }
                                if ((tabla.getValueAt(x, y - 1)).equals("◙")) {
                                    tabla.setValueAt("•", x, y - 1);
                                }
                            } else {
                                if ((tabla.getValueAt(x + 1, y)).equals("◙")) {
                                    tabla.setValueAt("•", x + 1, y);
                                }
                            }
                        }
                        if (x == n - 1) {
                            if (y == 0) {
                                if ((tabla.getValueAt(x - 1, y)).equals("◙")) {
                                    tabla.setValueAt("•", x - 1, y);
                                }
                                if ((tabla.getValueAt(x, y + 1)).equals("◙")) {
                                    tabla.setValueAt("•", x, y + 1);
                                }
                            } else if (y == m - 1) {
                                if ((tabla.getValueAt(x - 1, y)).equals("◙")) {
                                    tabla.setValueAt("•", x - 1, y);
                                }
                                if ((tabla.getValueAt(x, y - 1)).equals("◙")) {
                                    tabla.setValueAt("•", x, y - 1);
                                }
                            } else {
                                if ((tabla.getValueAt(x - 1, y)).equals("◙")) {
                                    tabla.setValueAt("•", x - 1, y);
                                }
                            }
                        }
                        if (y == 0) {
                            if ((tabla.getValueAt(x, y + 1)).equals("◙")) {
                                tabla.setValueAt("•", x, y + 1);
                            }
                        }
                        if (y == m - 1) {
                            if ((tabla.getValueAt(x, y - 1)).equals("◙")) {
                                tabla.setValueAt("•", x, y - 1);
                            }
                        }
                    }
                }
            }
        } else {
            tabla.setValueAt("•", x, y);
        }
    }//GEN-LAST:event_tablaMousePressed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void tablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseReleased


    }//GEN-LAST:event_tablaMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       bur.setVisible(false);
       ini.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Burbujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Burbujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Burbujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Burbujas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Burbujas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
